export const BOARD_REPOSITORY = Symbol('BOARD_REPOSITORY');
export const FEEDBACK_REPOSITORY = Symbol('FEEDBACK_REPOSITORY');
export const VOTE_REPOSITORY = Symbol('VOTE_REPOSITORY');
export const COMMENT_REPOSITORY = Symbol('COMMENT_REPOSITORY');
